[project]
name = "pyqt-dataframe-table"
version = "0.1.0"
description = ""
license = "MIT"
readme = "README.md"
dependencies = [
    "loguru>=0.7.3",
    "pandas>=2.3.1",
]

[project.optional-dependencies]
pyside = [
    "pyside6>=6.9.1",
]
pyqt = [
    "pyqt6>=6.9.1",
]


