[project]
name = "pyqt-dataframe-table"
version = "0.1.0"
description = ""
license = "MIT"
readme = "README.md"
dependencies = [
    "pandas>=2.3.1",
]

[project.optional-dependencies]
pyside = [
    "pyside6",
]
pyqt = [
    "pyqt6",
]


